/**
 * Export auto-generated OpenAPI 3.0 specs from observed API traffic.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { PrismaClient } from "@prisma/client";

interface OpenApiDocument {
  openapi: string;
  info: { title: string; description: string; version: string };
  servers: Array<{ url: string; description: string }>;
  paths: Record<string, PathItem>;
  components: { schemas: Record<string, unknown> };
}

interface PathItem {
  [method: string]: OperationObject;
}

interface OperationObject {
  summary: string;
  operationId: string;
  tags: string[];
  parameters: ParameterObject[];
  requestBody?: RequestBodyObject;
  responses: Record<string, ResponseObject>;
  "x-kyntra-health-score"?: number;
  "x-kyntra-p99-latency-ms"?: number;
}

interface ParameterObject {
  name: string;
  in: string;
  required: boolean;
  schema: { type: string };
  description?: string;
}

interface RequestBodyObject {
  required: boolean;
  content: { "application/json": { schema: { type: string; properties?: Record<string, unknown> } } };
}

interface ResponseObject {
  description: string;
  content?: { "application/json": { schema: { type: string; properties?: Record<string, unknown> } } };
}

export async function openapiRoutes(app: FastifyInstance, { prisma }: { prisma: PrismaClient }): Promise<void> {
  app.get("/v1/openapi", async (
    req: FastifyRequest<{ Querystring: { projectId: string; format?: "json" | "yaml" } }>,
    reply: FastifyReply
  ) => {
    const { projectId, format = "json" } = req.query;
    if (!projectId) return reply.status(400).send({ error: "projectId required" });

    const project = await prisma.project.findUnique({
      where: { id: projectId },
      select: { name: true },
    });

    if (!project) return reply.status(404).send({ error: "Project not found" });

    const endpoints = await prisma.apiEndpoint.findMany({
      where: { projectId },
      orderBy: [{ path: "asc" }, { method: "asc" }],
    });

    // Build OpenAPI document from endpoint observations
    const paths: Record<string, PathItem> = {};

    for (const endpoint of endpoints) {
      const openApiPath = endpoint.path.replace(/:(\w+)/g, "{$1}");
      const method = endpoint.method.toLowerCase();

      if (!paths[openApiPath]) paths[openApiPath] = {};

      // Extract path parameters
      const pathParams = [...endpoint.path.matchAll(/:(\w+)/g)].map((m) => ({
        name: m[1] ?? "id",
        in: "path",
        required: true,
        schema: { type: "string" },
        description: `Path parameter: ${m[1]}`,
      }));

      // Use observed OpenAPI spec if available, otherwise generate skeleton
      const observedSpec = endpoint.openApiSpec as {
        parameters?: ParameterObject[];
        responses?: Record<string, ResponseObject>;
        requestBody?: RequestBodyObject;
      } | null;

      const operation: OperationObject = {
        summary: `${endpoint.method} ${endpoint.path}`,
        operationId: `${method}${endpoint.path.replace(/[/:{}]/g, "_").replace(/_+/g, "_")}`,
        tags: [endpoint.path.split("/").filter(Boolean)[1] ?? "default"],
        parameters: observedSpec?.parameters ?? pathParams,
        responses: observedSpec?.responses ?? generateDefaultResponses(endpoint.method),
        "x-kyntra-health-score": endpoint.healthScore,
        "x-kyntra-p99-latency-ms": endpoint.p99LatencyMs,
      };

      if (observedSpec?.requestBody) {
        operation.requestBody = observedSpec.requestBody;
      } else if (["POST", "PUT", "PATCH"].includes(endpoint.method)) {
        operation.requestBody = {
          required: true,
          content: { "application/json": { schema: { type: "object" } } },
        };
      }

      paths[openApiPath]![method] = operation;
    }

    const document: OpenApiDocument = {
      openapi: "3.0.3",
      info: {
        title: `${project.name} API`,
        description: `Auto-generated OpenAPI spec from ${endpoints.length} observed endpoints. Generated by Kyntra.`,
        version: new Date().toISOString().split("T")[0] ?? "1.0.0",
      },
      servers: [{ url: "/", description: "Auto-detected from traffic" }],
      paths,
      components: { schemas: {} },
    };

    if (format === "yaml") {
      const yaml = jsonToYaml(document);
      return reply
        .header("Content-Type", "text/yaml")
        .header("Content-Disposition", `attachment; filename="${project.name.toLowerCase().replace(/\s+/g, "-")}-openapi.yaml"`)
        .send(yaml);
    }

    return reply
      .header("Content-Disposition", `attachment; filename="${project.name.toLowerCase().replace(/\s+/g, "-")}-openapi.json"`)
      .send(document);
  });
}

function generateDefaultResponses(method: string): Record<string, ResponseObject> {
  const successCode = method === "POST" ? "201" : "200";
  return {
    [successCode]: { description: "Success", content: { "application/json": { schema: { type: "object" } } } },
    "400": { description: "Bad Request" },
    "401": { description: "Unauthorized" },
    "404": { description: "Not Found" },
    "500": { description: "Internal Server Error" },
  };
}

function jsonToYaml(obj: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  if (obj === null || obj === undefined) return "null";
  if (typeof obj === "string") {
    if (obj.includes("\n") || obj.includes(":") || obj.includes("#")) {
      return `"${obj.replace(/"/g, '\\"')}"`;
    }
    return obj;
  }
  if (typeof obj === "number" || typeof obj === "boolean") return String(obj);
  if (Array.isArray(obj)) {
    if (obj.length === 0) return "[]";
    return "\n" + obj.map((item) => `${pad}- ${jsonToYaml(item, indent + 1)}`).join("\n");
  }
  if (typeof obj === "object") {
    const entries = Object.entries(obj as Record<string, unknown>);
    if (entries.length === 0) return "{}";
    return "\n" + entries
      .map(([k, v]) => `${pad}${k}: ${jsonToYaml(v, indent + 1)}`)
      .join("\n");
  }
  return String(obj);
}
