/**
 * Generate Playwright test scripts from recorded UI event sessions.
 */

import type { CorrelatedSession } from "./session-correlator.js";

export interface GeneratedPlaywrightTest {
  filename: string;
  content: string;
  testCount: number;
  description: string;
}

/**
 * Generate a Playwright test from a correlated session recording.
 */
export function generatePlaywrightTestFromSession(
  session: CorrelatedSession,
  baseUrl: string,
  testName?: string
): GeneratedPlaywrightTest {
  const name = testName ?? `User session ${session.sessionId.slice(0, 8)}`;
  const steps = buildTestSteps(session, baseUrl);

  const content = `import { test, expect, type Page } from '@playwright/test';

/**
 * Generated by Kyntra from user session ${session.sessionId}
 * Session duration: ${session.performanceMetrics.totalSessionDurationMs}ms
 * API calls: ${session.performanceMetrics.totalApiCalls}
 * Errors recorded: ${session.performanceMetrics.errorCount}
 */

const BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? '${baseUrl}';

test.describe('${name}', () => {
  test.beforeEach(async ({ page }) => {
    // Set viewport to match recorded session
    await page.setViewportSize({ width: 1280, height: 720 });
  });

${steps.map((step) => step.testCode).join("\n\n")}
});
`;

  return {
    filename: `${name.toLowerCase().replace(/\s+/g, "-")}.spec.ts`,
    content,
    testCount: steps.length,
    description: `Generated from session ${session.sessionId} with ${session.funnelSteps.length} funnel steps`,
  };
}

interface TestStep {
  description: string;
  testCode: string;
}

function buildTestSteps(session: CorrelatedSession, baseUrl: string): TestStep[] {
  const steps: TestStep[] = [];

  // Step 1: Navigation flow test
  if (session.pageViews.length > 0) {
    const navigationCode = session.funnelSteps.slice(0, 10).map((step, i) => {
      const path = step.name;
      return `    // Step ${i + 1}: Navigate to ${path}
    await page.goto(BASE_URL + '${path}');
    await page.waitForLoadState('networkidle');
    await expect(page).toHaveURL(new RegExp('${path.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&")}'));`;
    }).join("\n");

    steps.push({
      description: "Page navigation flow",
      testCode: `  test('should follow the recorded navigation flow', async ({ page }) => {
${navigationCode}
  });`,
    });
  }

  // Step 2: API contract tests (one per unique endpoint)
  const uniqueEndpoints = [
    ...new Map(session.apiCalls.map((c) => [c.path, c])).values(),
  ].slice(0, 8);

  for (const call of uniqueEndpoints) {
    if (call.statusCode >= 500) continue; // Don't replay server errors

    const testCode = `  test('API: ${call.method} ${call.path} should respond correctly', async ({ request }) => {
    const response = await request.${call.method.toLowerCase()}(\`\${BASE_URL}${call.path}\`);
    // Accept any 2xx or 3xx response (we recorded ${call.statusCode})
    expect(response.status()).toBeLessThan(400);
  });`;

    steps.push({ description: `API test: ${call.method} ${call.path}`, testCode });
  }

  // Step 3: Error scenario tests
  const apiErrors = session.errors.filter((e) => e.type === "api_error").slice(0, 3);
  if (apiErrors.length > 0) {
    const errorChecks = apiErrors
      .map((e) => `    // Error: ${e.message}\n    // Verify error is handled gracefully`)
      .join("\n");

    steps.push({
      description: "Error handling",
      testCode: `  test('should handle API errors gracefully', async ({ page }) => {
    // This test verifies that errors from the recorded session are handled
${errorChecks}
    // Navigate to the page that had errors
    await page.goto(BASE_URL + '${session.pageViews[0] ?? "/"}');
    // Check no unhandled error dialogs appear
    page.on('dialog', async (dialog) => {
      expect(dialog.type()).not.toBe('alert');
      await dialog.dismiss();
    });
    await page.waitForLoadState('networkidle');
  });`,
    });
  }

  // Step 4: Performance test
  steps.push({
    description: "Performance baseline",
    testCode: `  test('page should meet performance baseline from recorded session', async ({ page }) => {
    const startTime = Date.now();
    await page.goto(BASE_URL + '${session.pageViews[0] ?? "/"}');
    await page.waitForLoadState('networkidle');
    const loadTime = Date.now() - startTime;
    // Allow 2x the recorded baseline (${session.performanceMetrics.avgApiLatencyMs}ms avg API latency)
    expect(loadTime).toBeLessThan(${Math.max(5000, session.performanceMetrics.avgApiLatencyMs * 10)});
  });`,
  });

  return steps;
}

/**
 * Generate a Playwright config file for the project.
 */
export function generatePlaywrightConfig(baseUrl: string): string {
  return `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests/e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [
    ['html'],
    ['json', { outputFile: 'test-results/results.json' }],
  ],
  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL ?? '${baseUrl}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
    },
  ],
});
`;
}
