/**
 * Post Kyntra AI review results as GitHub PR comments.
 */
import type { CodeReviewOutput, ReviewComment, Severity } from "@kyntra/shared";

const GITHUB_API = "https://api.github.com";

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🔵",
  info: "⚪",
};

const CATEGORY_LABEL: Record<string, string> = {
  security: "Security",
  performance: "Performance",
  bug: "Bug",
  maintainability: "Maintainability",
  test_coverage: "Test Coverage",
  api_contract: "API Contract",
};

/**
 * Post a summary review comment on the PR.
 */
export async function postPrReviewSummary(
  repoFullName: string,
  prNumber: number,
  token: string,
  review: CodeReviewOutput,
  riskScore: number
): Promise<void> {
  const riskEmoji = riskScore >= 80 ? "🔴" : riskScore >= 50 ? "🟡" : "🟢";
  const criticalCount = review.comments.filter((c) => c.severity === "critical").length;
  const highCount = review.comments.filter((c) => c.severity === "high").length;

  const commentLines: string[] = [
    "## 🤖 Kyntra AI Code Review",
    "",
    `**Risk Score:** ${riskEmoji} ${riskScore}/100`,
    "",
    `**Summary:** ${review.summary}`,
    "",
    "### Issues Found",
    "",
    `| Severity | Count |`,
    `|----------|-------|`,
    `| 🔴 Critical | ${criticalCount} |`,
    `| 🟠 High | ${highCount} |`,
    `| 🟡 Medium | ${review.comments.filter((c) => c.severity === "medium").length} |`,
    `| 🔵 Low | ${review.comments.filter((c) => c.severity === "low").length} |`,
    "",
  ];

  if (review.positives.length > 0) {
    commentLines.push("### ✅ What's Good", "");
    for (const p of review.positives) {
      commentLines.push(`- ${p}`);
    }
    commentLines.push("");
  }

  if (review.suggestedTests.length > 0) {
    commentLines.push("### 🧪 Suggested Tests", "");
    for (const t of review.suggestedTests) {
      commentLines.push(`- ${t}`);
    }
    commentLines.push("");
  }

  commentLines.push("---");
  commentLines.push("*Generated by [Kyntra](https://kyntra.io) — AI Engineering Intelligence*");

  await fetch(`${GITHUB_API}/repos/${repoFullName}/issues/${prNumber}/comments`, {
    method: "POST",
    headers: {
      Authorization: `token ${token}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
      "User-Agent": "Kyntra/1.0",
    },
    body: JSON.stringify({ body: commentLines.join("\n") }),
  });
}

/**
 * Post inline review comments on specific lines of the PR diff.
 */
export async function postInlineReviewComments(
  repoFullName: string,
  prNumber: number,
  commitSha: string,
  token: string,
  comments: ReviewComment[]
): Promise<void> {
  if (comments.length === 0) return;

  // Only post critical and high severity as inline comments to avoid noise
  const inlineComments = comments
    .filter((c) => c.severity === "critical" || c.severity === "high")
    .slice(0, 20) // GitHub limits review comments
    .map((c) => ({
      path: c.filePath,
      line: c.lineEnd,
      side: "RIGHT" as const,
      body: [
        `${SEVERITY_EMOJI[c.severity]} **${CATEGORY_LABEL[c.category] ?? c.category}** (${c.severity})`,
        "",
        c.message,
        ...(c.suggestion ? ["", `**Suggestion:** ${c.suggestion}`] : []),
        ...(c.autoFixable ? ["", "*This issue may be auto-fixable.*"] : []),
      ].join("\n"),
    }));

  if (inlineComments.length === 0) return;

  const response = await fetch(
    `${GITHUB_API}/repos/${repoFullName}/pulls/${prNumber}/reviews`,
    {
      method: "POST",
      headers: {
        Authorization: `token ${token}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
        "User-Agent": "Kyntra/1.0",
      },
      body: JSON.stringify({
        commit_id: commitSha,
        event: "COMMENT",
        comments: inlineComments,
      }),
    }
  );

  if (!response.ok) {
    const text = await response.text();
    console.error(`Failed to post inline comments: ${response.status} ${text}`);
  }
}

/**
 * Update the PR check status via GitHub Checks API.
 */
export async function updatePrCheckStatus(
  repoFullName: string,
  headSha: string,
  token: string,
  riskScore: number,
  summary: string
): Promise<void> {
  const conclusion = riskScore >= 80 ? "failure" : riskScore >= 50 ? "neutral" : "success";

  await fetch(`${GITHUB_API}/repos/${repoFullName}/check-runs`, {
    method: "POST",
    headers: {
      Authorization: `token ${token}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
      "User-Agent": "Kyntra/1.0",
    },
    body: JSON.stringify({
      name: "Kyntra AI Review",
      head_sha: headSha,
      status: "completed",
      conclusion,
      output: {
        title: `Risk Score: ${riskScore}/100`,
        summary,
      },
    }),
  });
}
